import { FactsBundle } from '../../types/analysis.ts';

export const DEMO_PROFILES: Record<string, FactsBundle> = {
  'alex-student-dev': {
    username: 'alex-student-dev',
    userType: 'User',
    totalScore: 42,
    grade: 'Roast-worthy',
    metrics: {
      username: 'alex-student-dev',
      accountAgeYears: 2.1,
      publicRepoCount: 19,
      forkedRepoCount: 8,
      originalRepoCount: 11,
      hasCustomAvatar: true,
      nameProvided: true,
      bioLength: 14,
      locationProvided: false,
      websiteProvided: false,
      companyProvided: false,
      hasProfileReadme: false,
      profileReadmeLength: 0,
      totalStars: 4,
      totalForks: 1,
      topLanguages: [
        { language: 'JavaScript', bytes: 142000, percentage: 55 },
        { language: 'Python', bytes: 64000, percentage: 25 },
        { language: 'HTML', bytes: 51000, percentage: 20 },
      ],
      activeWeeksLast6Months: 4,
      daysSinceLastPush: 38,
      finishRate: 0.21,
      tutorialHellCount: 4,
      suspiciousGenericReposCount: 5,
      flaggedSecretRepos: ['my-mern-app'],
      flaggedJunkTreeRepos: ['react-weather-test'],
      overallGenericCommitRate: 64,
    },
    categoryScores: {
      profileBasics: {
        score: 6,
        max: 15,
        label: 'Profile Basics',
        breakdown: ['Photo set (+3)', 'Name provided (+3)', 'Bio too short (<20 chars)', 'No portfolio link', 'No location'],
      },
      profileReadme: {
        score: 0,
        max: 10,
        label: 'Profile README',
        breakdown: ['Missing username/username profile README (0/10)'],
      },
      projectQuality: {
        score: 11,
        max: 25,
        label: 'Project Quality',
        breakdown: ['Only 2 of 6 repos have descriptions', 'No live demo URLs on any repository', 'Missing open-source licenses'],
      },
      readmeQuality: {
        score: 8,
        max: 20,
        label: 'README Quality',
        breakdown: ['Average README length is 94 characters', 'Zero screenshots or demo GIFs found', 'No setup or installation guides'],
      },
      activityConsistency: {
        score: 5,
        max: 15,
        label: 'Activity & Consistency',
        breakdown: ['Only 4 active weeks in last 6 months', 'Last push was 38 days ago (inactive cooldown)'],
      },
      finishRateFocus: {
        score: 3,
        max: 10,
        label: 'Finish Rate & Focus',
        breakdown: ['4 tutorial clones detected (todo-app, calculator, etc.)', 'High ratio of unfinished or abandoned repos'],
      },
      communitySignals: {
        score: 2,
        max: 5,
        label: 'Community Signals',
        breakdown: ['4 stars total across all repos', 'No public contributions to open-source projects'],
      },
    },
    flags: [
      {
        id: 'flag-secret',
        type: 'red',
        title: 'Exposed .env / Secret File Detected',
        description: 'Repository "my-mern-app" appears to have a committed .env or credentials file.',
        severity: 'critical',
        repo: 'my-mern-app',
      },
      {
        id: 'flag-node-modules',
        type: 'red',
        title: 'Committed node_modules in repository',
        description: 'Repository "react-weather-test" has node_modules checked into Git history. Add a .gitignore immediately.',
        severity: 'warning',
        repo: 'react-weather-test',
      },
      {
        id: 'flag-commit-messages',
        type: 'red',
        title: '64% Low-Effort Commit Messages',
        description: 'Frequent commits with messages like "update", "fix", "changes", "wip".',
        severity: 'warning',
      },
      {
        id: 'flag-tutorial-hell',
        type: 'red',
        title: 'Tutorial Graveyard Syndrome',
        description: 'Found repos named "todo-app", "weather-app", "calculator", "portfolio-clone" with default boilerplate.',
        severity: 'warning',
      },
      {
        id: 'flag-green-avatar',
        type: 'green',
        title: 'Custom Profile Picture',
        description: 'You replaced the default GitHub identicon avatar.',
      },
      {
        id: 'flag-green-lang',
        type: 'green',
        title: 'Multi-Language Foundation',
        description: 'Has worked with both JavaScript and Python.',
      },
    ],
    topRepos: [
      {
        name: 'my-mern-app',
        fullName: 'alex-student-dev/my-mern-app',
        description: 'Full stack app project',
        isFork: false,
        isArchived: false,
        stars: 2,
        forks: 0,
        language: 'JavaScript',
        languages: { JavaScript: 85000, CSS: 12000 },
        pushedAt: '2026-08-14T10:00:00Z',
        createdAt: '2025-11-01T08:00:00Z',
        sizeKb: 1420,
        homepage: null,
        topics: ['mern', 'mongodb'],
        license: null,
        hasIssues: true,
        hasReadme: true,
        readmeLength: 120,
        readmeSections: {
          hasTitle: true,
          hasInstall: false,
          hasUsage: false,
          hasScreenshotOrMedia: false,
          hasTechStack: false,
          hasFeatures: false,
        },
        hasGitignore: false,
        hasLicenseFile: false,
        hasTests: false,
        hasCiWorkflow: false,
        committedSecretsOrEnv: true,
        committedNodeModulesOrVenv: false,
        totalSampledCommits: 22,
        genericCommitCount: 15,
        genericCommitPercentage: 68,
        healthScore: 32,
        healthGrade: 'F',
      },
      {
        name: 'react-weather-test',
        fullName: 'alex-student-dev/react-weather-test',
        description: null,
        isFork: false,
        isArchived: false,
        stars: 1,
        forks: 0,
        language: 'JavaScript',
        languages: { JavaScript: 45000 },
        pushedAt: '2026-07-20T10:00:00Z',
        createdAt: '2026-01-10T08:00:00Z',
        sizeKb: 34000,
        homepage: null,
        topics: [],
        license: null,
        hasIssues: false,
        hasReadme: false,
        readmeLength: 0,
        readmeSections: {
          hasTitle: false,
          hasInstall: false,
          hasUsage: false,
          hasScreenshotOrMedia: false,
          hasTechStack: false,
          hasFeatures: false,
        },
        hasGitignore: false,
        hasLicenseFile: false,
        hasTests: false,
        hasCiWorkflow: false,
        committedSecretsOrEnv: false,
        committedNodeModulesOrVenv: true,
        totalSampledCommits: 10,
        genericCommitCount: 8,
        genericCommitPercentage: 80,
        healthScore: 18,
        healthGrade: 'F',
      },
      {
        name: 'py-scraper-bot',
        fullName: 'alex-student-dev/py-scraper-bot',
        description: 'Scrapes e-commerce prices with BeautifulSoup and notifies discord',
        isFork: false,
        isArchived: false,
        stars: 1,
        forks: 1,
        language: 'Python',
        languages: { Python: 32000 },
        pushedAt: '2026-09-01T10:00:00Z',
        createdAt: '2026-03-01T08:00:00Z',
        sizeKb: 480,
        homepage: null,
        topics: ['python', 'web-scraping'],
        license: 'MIT',
        hasIssues: true,
        hasReadme: true,
        readmeLength: 540,
        readmeSections: {
          hasTitle: true,
          hasInstall: true,
          hasUsage: true,
          hasScreenshotOrMedia: false,
          hasTechStack: true,
          hasFeatures: true,
        },
        hasGitignore: true,
        hasLicenseFile: true,
        hasTests: false,
        hasCiWorkflow: false,
        committedSecretsOrEnv: false,
        committedNodeModulesOrVenv: false,
        totalSampledCommits: 14,
        genericCommitCount: 4,
        genericCommitPercentage: 28,
        healthScore: 68,
        healthGrade: 'C',
      },
    ],
    rescueSkeleton: [
      {
        id: 'rescue-secrets',
        priority: 1,
        title: 'Revoke and delete exposed secrets in my-mern-app',
        why: 'Committed secrets and .env files are an immediate security risk and an instant disqualifier in technical interviews.',
        steps: [
          'Rotate/invalidate any leaked database passwords or API keys immediately.',
          'Add .env to your .gitignore file.',
          'Run git rm --cached .env to un-track the file without deleting local config.',
        ],
        effort: '15 min',
        impact: 'High',
        category: 'security',
        repoTarget: 'my-mern-app',
      },
      {
        id: 'rescue-profile-readme',
        priority: 2,
        title: 'Create your GitHub Profile README (username/username)',
        why: 'Recruiters spend an average of 15-30 seconds on a profile. Without a profile README, your landing page is empty.',
        steps: [
          'Create a public repo named alex-student-dev/alex-student-dev with a README.md file.',
          'Introduce your core tech stack, what you are currently building, and link your resume or LinkedIn.',
          'Highlight 2 flagship projects with 1-sentence summaries and live links.',
        ],
        effort: '15 min',
        impact: 'High',
        category: 'profile',
      },
      {
        id: 'rescue-flagship-readme',
        priority: 3,
        title: 'Turn py-scraper-bot into your showcase flagship project',
        why: 'py-scraper-bot solves an actual problem. With a recorded GIF and clean docs, it becomes interview-ready.',
        steps: [
          'Record a 10-second GIF of the bot scraping and posting to Discord, and embed it at the top of README.',
          'Document required environment variables (DISCORD_WEBHOOK_URL, TARGET_URL).',
          'Add a sample requirements.txt and quickstart instruction.',
        ],
        effort: '1 hour',
        impact: 'High',
        category: 'flagship',
        repoTarget: 'py-scraper-bot',
      },
      {
        id: 'rescue-cleanup',
        priority: 4,
        title: 'Purge node_modules & archive empty tutorial repos',
        why: 'Bloated repositories with 34MB of checked-in node_modules show a lack of Git fundamentals to senior engineers.',
        steps: [
          'In react-weather-test: add node_modules/ to .gitignore and git rm -r --cached node_modules.',
          'Archive or make private 4 abandoned tutorial test repos.',
          'Pin your top 3 curated projects to your profile page.',
        ],
        effort: '15 min',
        impact: 'Medium',
        category: 'cleanup',
        repoTarget: 'react-weather-test',
      },
      {
        id: 'rescue-activity',
        priority: 5,
        title: 'Establish a 2-commit per week consistency rhythm',
        why: 'Long dead gaps make recruiters wonder if you have coded recently or kept your skills sharp.',
        steps: [
          'Set a weekly goal: ship 1 small feature or documentation improvement every Tuesday and Saturday.',
          'Write clear, imperative commit messages (e.g., "Add Discord webhook retry logic").',
        ],
        effort: 'Weekend',
        impact: 'Medium',
        category: 'activity',
      },
    ],
    isBlankSlate: false,
  },
  'shadcn': {
    username: 'shadcn',
    userType: 'User',
    totalScore: 96,
    grade: 'Hire-ready',
    metrics: {
      username: 'shadcn',
      accountAgeYears: 7.5,
      publicRepoCount: 28,
      forkedRepoCount: 2,
      originalRepoCount: 26,
      hasCustomAvatar: true,
      nameProvided: true,
      bioLength: 35,
      locationProvided: true,
      websiteProvided: true,
      companyProvided: true,
      hasProfileReadme: true,
      profileReadmeLength: 850,
      totalStars: 85000,
      totalForks: 7800,
      topLanguages: [
        { language: 'TypeScript', bytes: 840000, percentage: 80 },
        { language: 'CSS', bytes: 120000, percentage: 12 },
        { language: 'JavaScript', bytes: 70000, percentage: 8 },
      ],
      activeWeeksLast6Months: 24,
      daysSinceLastPush: 2,
      finishRate: 0.92,
      tutorialHellCount: 0,
      suspiciousGenericReposCount: 0,
      flaggedSecretRepos: [],
      flaggedJunkTreeRepos: [],
      overallGenericCommitRate: 14,
    },
    categoryScores: {
      profileBasics: {
        score: 15,
        max: 15,
        label: 'Profile Basics',
        breakdown: ['Photo set (+3)', 'Name provided (+3)', 'Descriptive bio (+4)', 'Portfolio link (+2)', 'Location (+2)', 'Affiliation (+1)'],
      },
      profileReadme: {
        score: 10,
        max: 10,
        label: 'Profile README',
        breakdown: ['High-impact Profile README (+10)'],
      },
      projectQuality: {
        score: 25,
        max: 25,
        label: 'Project Quality',
        breakdown: ['All top repositories have clear descriptions, topics, and live documentation links'],
      },
      readmeQuality: {
        score: 20,
        max: 20,
        label: 'README Quality',
        breakdown: ['World-class documentation with quickstarts, components previews, and shields'],
      },
      activityConsistency: {
        score: 15,
        max: 15,
        label: 'Activity & Consistency',
        breakdown: ['Consistent weekly shipping cadence (+10)', 'Active push within last 48 hours (+5)'],
      },
      finishRateFocus: {
        score: 10,
        max: 10,
        label: 'Finish Rate & Focus',
        breakdown: ['Exceptional finish rate (+5)', 'Multiple legendary flagship repositories (+5)'],
      },
      communitySignals: {
        score: 5,
        max: 5,
        label: 'Community Signals',
        breakdown: ['85,000+ stars across repositories (+5)'],
      },
    },
    flags: [
      {
        id: 'flag-star-legend',
        type: 'green',
        title: 'Massive Open Source Community Traction',
        description: 'Over 85,000 stars across open source repositories.',
      },
      {
        id: 'flag-flagship-ui',
        type: 'green',
        title: 'Industry-Standard Flagship Project',
        description: 'Repository "ui" is one of the most widely adopted component architectures globally.',
      },
    ],
    topRepos: [
      {
        name: 'ui',
        fullName: 'shadcn/ui',
        description: 'Beautifully designed components that you can copy and paste into your apps.',
        isFork: false,
        isArchived: false,
        stars: 76000,
        forks: 6900,
        language: 'TypeScript',
        languages: { TypeScript: 650000, CSS: 95000 },
        pushedAt: '2026-10-06T18:00:00Z',
        createdAt: '2023-01-15T08:00:00Z',
        sizeKb: 14200,
        homepage: 'https://ui.shadcn.com',
        topics: ['components', 'react', 'tailwind', 'radix-ui'],
        license: 'MIT',
        hasIssues: true,
        hasReadme: true,
        readmeLength: 4200,
        readmeSections: {
          hasTitle: true,
          hasInstall: true,
          hasUsage: true,
          hasScreenshotOrMedia: true,
          hasTechStack: true,
          hasFeatures: true,
        },
        hasGitignore: true,
        hasLicenseFile: true,
        hasTests: true,
        hasCiWorkflow: true,
        committedSecretsOrEnv: false,
        committedNodeModulesOrVenv: false,
        totalSampledCommits: 25,
        genericCommitCount: 2,
        genericCommitPercentage: 8,
        healthScore: 98,
        healthGrade: 'A',
      },
    ],
    rescueSkeleton: [
      {
        id: 'rescue-maintainer-life',
        priority: 1,
        title: 'Maintain work-life balance and automate triage',
        why: 'With 76,000+ stars, issue fatigue is the number one hazard.',
        steps: [
          'Enable GitHub issue templates and automated labeling bots.',
          'Delegate triage to trusted community contributors.',
        ],
        effort: '1 hour',
        impact: 'High',
        category: 'activity',
      },
    ],
    isBlankSlate: false,
  },
  'priya-fullstack': {
    username: 'priya-fullstack',
    userType: 'User',
    totalScore: 84,
    grade: 'Solid',
    metrics: {
      username: 'priya-fullstack',
      accountAgeYears: 2.4,
      publicRepoCount: 14,
      forkedRepoCount: 2,
      originalRepoCount: 12,
      hasCustomAvatar: true,
      nameProvided: true,
      bioLength: 48,
      locationProvided: true,
      websiteProvided: true,
      companyProvided: false,
      hasProfileReadme: true,
      profileReadmeLength: 680,
      totalStars: 28,
      totalForks: 6,
      topLanguages: [
        { language: 'TypeScript', bytes: 320000, percentage: 50 },
        { language: 'Python', bytes: 190000, percentage: 30 },
        { language: 'CSS', bytes: 120000, percentage: 20 },
      ],
      activeWeeksLast6Months: 14,
      daysSinceLastPush: 4,
      finishRate: 0.65,
      tutorialHellCount: 0,
      suspiciousGenericReposCount: 1,
      flaggedSecretRepos: [],
      flaggedJunkTreeRepos: [],
      overallGenericCommitRate: 14,
    },
    categoryScores: {
      profileBasics: {
        score: 14,
        max: 15,
        label: 'Profile Basics',
        breakdown: ['Photo set (+3)', 'Name provided (+3)', 'Bio provided (+4)', 'Location provided (+2)', 'Portfolio link set (+2)'],
      },
      profileReadme: {
        score: 10,
        max: 10,
        label: 'Profile README',
        breakdown: ['Comprehensive profile README with skills and demo links (+10/10)'],
      },
      projectQuality: {
        score: 22,
        max: 25,
        label: 'Project Quality',
        breakdown: ['5 of 6 repos have descriptions', 'Live demo links on 3 repositories', 'Open-source licenses set (+22/25)'],
      },
      readmeQuality: {
        score: 17,
        max: 20,
        label: 'README Quality',
        breakdown: ['Architecture diagrams and setup instructions included (+17/20)'],
      },
      activityConsistency: {
        score: 13,
        max: 15,
        label: 'Activity & Consistency',
        breakdown: ['Pushed 4 days ago (+5)', 'Consistent coding rhythm over last 6 months (+8)'],
      },
      finishRateFocus: {
        score: 8,
        max: 10,
        label: 'Finish Rate & Focus',
        breakdown: ['High completion rate on original projects', 'No generic tutorial clones'],
      },
      communitySignals: {
        score: 3,
        max: 5,
        label: 'Community Signals',
        breakdown: ['28 stars across repositories (+3/5)'],
      },
    },
    flags: [
      {
        id: 'flag-live-demos',
        type: 'green',
        title: '3 Live Demo URLs deployed',
        description: 'Projects have deployed instances on Vercel and Render for immediate recruiter review.',
      },
    ],
    topRepos: [
      {
        name: 'taskflow-pro',
        fullName: 'priya-fullstack/taskflow-pro',
        description: 'Real-time collaborative kanban board with websockets and role-based permissions',
        isFork: false,
        isArchived: false,
        stars: 19,
        forks: 4,
        language: 'TypeScript',
        languages: { TypeScript: 240000, CSS: 45000 },
        pushedAt: '2026-10-04T12:00:00Z',
        createdAt: '2025-02-10T00:00:00Z',
        sizeKb: 6500,
        homepage: 'https://taskflow-pro.vercel.app',
        topics: ['typescript', 'react', 'websockets'],
        license: 'MIT',
        hasIssues: true,
        hasReadme: true,
        readmeLength: 1400,
        readmeSections: {
          hasTitle: true,
          hasInstall: true,
          hasUsage: true,
          hasScreenshotOrMedia: true,
          hasTechStack: true,
          hasFeatures: true,
        },
        hasGitignore: true,
        hasLicenseFile: true,
        hasTests: true,
        hasCiWorkflow: true,
        committedSecretsOrEnv: false,
        committedNodeModulesOrVenv: false,
        totalSampledCommits: 22,
        genericCommitCount: 3,
        genericCommitPercentage: 13,
        healthScore: 95,
        healthGrade: 'A',
      },
    ],
    rescueSkeleton: [
      {
        id: 'rescue-priya-perf',
        priority: 1,
        title: 'Add a Lighthouse performance badge to taskflow-pro',
        why: 'Demonstrating 95+ web vitals immediately catches technical lead attention.',
        steps: ['Run Lighthouse audit', 'Embed badge in README.md'],
        effort: '15 min',
        impact: 'Medium',
        category: 'flagship',
      },
    ],
    isBlankSlate: false,
  },
};
